# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fb3814d46a7e4b62545f2eecf7a8798c0510ac82d9075bc124be547efceda41daa275350184901d139547821f902e9f9b680659e502cf39afe08c3ffe502fe7

test:
  secret_key_base: 4b410d16420be85b2d75960d45e1fe8ec6da324e914753477368c681eeff2a7725fcd49c2563a96782532c08b88dfbf9d347e70888a65227e701a8a3f571098a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
